permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: Anderson
  email: imnotanderson@gmail.com
  link: http://holyhigh.xyz
#  weibo: http://weibo.com/yansu0711
  github: http://github.com/imnotanderson

# 站点信息
title: Holyhigh
description: Anderson's Blog
url: http://Holyhigh.xyz
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars0.githubusercontent.com/u/4974768
favicon: #http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: holyhigh

#duoshuo 设置
duoshuo:
  shootname: holyhigh
